# Generated by Django 4.2.5 on 2023-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparacao_medidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaMedidasCalca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ombro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('torax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento_manga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento_perna', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaMedidasJaqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ombro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('torax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento_manga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento_perna', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
